name: India Power API Sync

on:
  schedule:
    - cron: '30 4 * * *' # 10:00 AM IST
  workflow_dispatch: # Allows manual run

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important: allows the bot to save the JSON file
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install pandas xlrd requests openpyxl

      - name: Run Scraper
        run: python update_data.py

      - name: Commit and Push
        run: |
          git config --global user.name "PowerBot"
          git config --global user.email "bot@github.com"
          git add power_data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Daily Update" && git push)
          
